### ISSUE TITLE
Initial icon size?

### ISSUE THREAD

**Issue by StorytellerCZ** [LiteraryUniverse/icons#1]
Right now the view area of the SVG icons is 24x24. I don't know if that is good or bad.

Rocket.chat in their icons starts with 32x32: https://github.com/RocketChat/fuselage/tree/develop/packages/icons

What do you think @HScono, should we re-do the icons at that size or maybe a different size? We will need to revise all the icons anyway for proper naming conventions so we can consider making changes like this as well.

**Comment by HScono** [comment]
in the design assets i prepared for 3 different size, which is 24x24, 32x32, and the largest on is 42x42. The size usage is different on some certain of page.  but overall the 32x32 px is the most size that we will be using since that will lot of appear in the body pages,

**Comment by StorytellerCZ** [comment]
Let's go with 32px. Also in the next release I will fix few icon names to shape instead of function.

**Comment by StorytellerCZ** [comment]
Finished in v0.4
